(ns guard-testing.teleport
  (:require [org.clojars.cognesence.breadth-search.core :refer :all]
            [org.clojars.cognesence.matcher.core :refer :all]
            [org.clojars.cognesence.ops-search.core :refer :all]))

(comment "Guard that room 1 and room 2 aren't the same room.
          Also guard that tele 1 and tele 2 aren't the same tele.
          Does having 2 separate guards work better than using an AND?
          Can guard be used to specify 'teleporter-connection ?tele1 ?tele2' OR 'teleporter-connection ?tele2 ?tele2'?")

(def op-teleport-base
  '{teleport {:pre ((agent ?agent)
                    (teleporter ?tele1)
                    (teleporter ?tele2)
                    (powerable ?tele1)
                    (powerable ?tele2)
                    (in ?agent ?room1)
                    (in ?tele1 ?room1)
                    (in ?tele2 ?room2)
                    (teleporter-connection ?tele1 ?tele2)
                    (powered ?tele1 true)
                    (powered ?tele2 true)
                    )
              :add ((in ?agent ?room2))
              :del ((in ?agent ?room1))
              :txt ((?agent has transported from ?tele1 in ?room1 to ?tele2 in ?room2))
              }
    }
  )

(def op-teleport-guarded-one
  '{teleport {:pre ((agent ?agent)
                    (teleporter ?tele1)
                    (teleporter ?tele2)
                    (powerable ?tele1)
                    (powerable ?tele2)
                    (in ?agent ?room1)
                    (in ?tele1 ?room1)
                    (in ?tele2 ?room2)
                    (:guard (not= (? room1) (? room2)))
                    (teleporter-connection ?tele1 ?tele2)
                    (powered ?tele1 true)
                    (powered ?tele2 true)
                    (:guard (not= (? tele1) (? tele2)))
                    )
              :add ((in ?agent ?room2))
              :del ((in ?agent ?room1))
              :txt ((?agent has transported from ?tele1 in ?room1 to ?tele2 in ?room2))
              }
    }
  )

(def op-teleport-guarded-two
  '{teleport {:pre ((agent ?agent)
                    (teleporter ?tele1)
                    (teleporter ?tele2)
                    (powerable ?tele1)
                    (powerable ?tele2)
                    (in ?agent ?room1)
                    (in ?tele1 ?room1)
                    (in ?tele2 ?room2)
                    (teleporter-connection ?tele1 ?tele2)
                    (powered ?tele1 true)
                    (powered ?tele2 true)
                    (:guard (and (not= (? room1) (? room2))
                                 (not= (? tele1) (? tele2))))
                    )
              :add ((in ?agent ?room2))
              :del ((in ?agent ?room1))
              :txt ((?agent has transported from ?tele1 in ?room1 to ?tele2 in ?room2))
              }
    }
  )

(def op-teleport-guarded-three
  '{teleport {:pre ((agent ?agent)
                    (teleporter ?tele1)
                    (teleporter ?tele2)
                    (powerable ?tele1)
                    (powerable ?tele2)
                    (in ?agent ?room1)
                    (in ?tele1 ?room1)
                    (in ?tele2 ?room2)
                    (teleporter-connection ?tele-con1 ?tele-con2)
                    (:guard (and (not= (? room1) (? room2))
                                 (not= (? tele1) (? tele2))
                                 (or (and (= (? tele-con1) (? tele1)) (= (? tele-con2) (? tele2)))
                                     (and (= (? tele-con2) (? tele1)) (= (? tele-con1) (? tele2))))
                            ))
                    (powered ?tele1 true)
                    (powered ?tele2 true)
                    )
              :add ((in ?agent ?room2))
              :del ((in ?agent ?room1))
              :txt ((?agent has transported from ?tele1 in ?room1 to ?tele2 in ?room2))
              }
    }
  )

(def state-teleport-small
  '#{(agent R)
     (in R A)

     (room A)
     (room B)

     (teleporter tele-A)
     (teleporter tele-B)
     (powerable tele-A)
     (powerable tele-B)
     (powered tele-A true)
     (powered tele-B true)
     (teleporter-connection tele-A tele-B)
     (teleporter-connection tele-B tele-A)

     (in tele-A A)
     (in tele-B B)
     }
  )

(def state-teleport-small-alt
  '#{(agent R)
     (in R A)

     (room A)
     (room B)

     (teleporter tele-A)
     (teleporter tele-B)
     (powerable tele-A)
     (powerable tele-B)
     (powered tele-A true)
     (powered tele-B true)
     (teleporter-connection tele-A tele-B)

     (in tele-A A)
     (in tele-B B)
     }
  )

(def state-teleport-medium
  '#{(agent R)
     (in R A)

     (room A)
     (room B)
     (room C)
     (room D)
     (room E)

     (teleporter tele-A)
     (teleporter tele-B)
     (teleporter tele-C)
     (teleporter tele-D)
     (teleporter tele-E)
     (powerable tele-A)
     (powerable tele-B)
     (powerable tele-C)
     (powerable tele-D)
     (powerable tele-E)
     (powered tele-A true)
     (powered tele-B true)
     (powered tele-C true)
     (powered tele-D true)
     (powered tele-E true)
     (teleporter-connection tele-A tele-B)
     (teleporter-connection tele-B tele-A)
     (teleporter-connection tele-B tele-C)
     (teleporter-connection tele-C tele-B)
     (teleporter-connection tele-C tele-D)
     (teleporter-connection tele-D tele-C)
     (teleporter-connection tele-D tele-E)
     (teleporter-connection tele-E tele-D)

     (in tele-A A)
     (in tele-B B)
     (in tele-C E)
     (in tele-D D)
     (in tele-E C)
     }
  )

(def state-teleport-medium-alt
  '#{(agent R)
     (in R A)

     (room A)
     (room B)
     (room C)
     (room D)
     (room E)

     (teleporter tele-A)
     (teleporter tele-B)
     (teleporter tele-C)
     (teleporter tele-D)
     (teleporter tele-E)
     (powerable tele-A)
     (powerable tele-B)
     (powerable tele-C)
     (powerable tele-D)
     (powerable tele-E)
     (powered tele-A true)
     (powered tele-B true)
     (powered tele-C true)
     (powered tele-D true)
     (powered tele-E true)
     (teleporter-connection tele-A tele-B)
     (teleporter-connection tele-B tele-C)
     (teleporter-connection tele-C tele-D)
     (teleporter-connection tele-D tele-E)

     (in tele-A A)
     (in tele-B B)
     (in tele-C E)
     (in tele-D D)
     (in tele-E C)
     }
  )

(def state-teleport-large
  '#{(agent R)
     (in R A)

     (room A)
     (room B)
     (room C)
     (room D)
     (room E)
     (room F)
     (room G)
     (room H)
     (room I)
     (room J)

     (teleporter tele-A)
     (teleporter tele-B)
     (teleporter tele-C)
     (teleporter tele-D)
     (teleporter tele-E)
     (teleporter tele-F)
     (teleporter tele-G)
     (teleporter tele-H)
     (teleporter tele-I)
     (teleporter tele-J)
     (powerable tele-A)
     (powerable tele-B)
     (powerable tele-C)
     (powerable tele-D)
     (powerable tele-E)
     (powerable tele-F)
     (powerable tele-G)
     (powerable tele-H)
     (powerable tele-I)
     (powerable tele-J)
     (powered tele-A true)
     (powered tele-B true)
     (powered tele-C true)
     (powered tele-D true)
     (powered tele-E true)
     (powered tele-F true)
     (powered tele-G true)
     (powered tele-H true)
     (powered tele-I true)
     (powered tele-J true)
     (teleporter-connection tele-A tele-B)
     (teleporter-connection tele-B tele-A)
     (teleporter-connection tele-B tele-C)
     (teleporter-connection tele-C tele-B)
     (teleporter-connection tele-C tele-D)
     (teleporter-connection tele-D tele-C)
     (teleporter-connection tele-D tele-E)
     (teleporter-connection tele-E tele-D)
     (teleporter-connection tele-E tele-F)
     (teleporter-connection tele-F tele-E)
     (teleporter-connection tele-F tele-G)
     (teleporter-connection tele-G tele-F)
     (teleporter-connection tele-G tele-H)
     (teleporter-connection tele-H tele-G)
     (teleporter-connection tele-H tele-I)
     (teleporter-connection tele-I tele-H)
     (teleporter-connection tele-I tele-J)
     (teleporter-connection tele-J tele-I)

     (in tele-A A)
     (in tele-B B)
     (in tele-C E)
     (in tele-D D)
     (in tele-E C)
     (in tele-F F)
     (in tele-G J)
     (in tele-H I)
     (in tele-I H)
     (in tele-J G)
     }
  )

(def state-teleport-large-alt
  '#{(agent R)
     (in R A)

     (room A)
     (room B)
     (room C)
     (room D)
     (room E)
     (room F)
     (room G)
     (room H)
     (room I)
     (room J)

     (teleporter tele-A)
     (teleporter tele-B)
     (teleporter tele-C)
     (teleporter tele-D)
     (teleporter tele-E)
     (teleporter tele-F)
     (teleporter tele-G)
     (teleporter tele-H)
     (teleporter tele-I)
     (teleporter tele-J)
     (powerable tele-A)
     (powerable tele-B)
     (powerable tele-C)
     (powerable tele-D)
     (powerable tele-E)
     (powerable tele-F)
     (powerable tele-G)
     (powerable tele-H)
     (powerable tele-I)
     (powerable tele-J)
     (powered tele-A true)
     (powered tele-B true)
     (powered tele-C true)
     (powered tele-D true)
     (powered tele-E true)
     (powered tele-F true)
     (powered tele-G true)
     (powered tele-H true)
     (powered tele-I true)
     (powered tele-J true)
     (teleporter-connection tele-A tele-B)
     (teleporter-connection tele-B tele-C)
     (teleporter-connection tele-C tele-D)
     (teleporter-connection tele-D tele-E)
     (teleporter-connection tele-E tele-F)
     (teleporter-connection tele-F tele-G)
     (teleporter-connection tele-G tele-H)
     (teleporter-connection tele-H tele-I)
     (teleporter-connection tele-I tele-J)

     (in tele-A A)
     (in tele-B B)
     (in tele-C E)
     (in tele-D D)
     (in tele-E C)
     (in tele-F F)
     (in tele-G J)
     (in tele-H I)
     (in tele-I H)
     (in tele-J G)
     }
  )


(def state-teleport-very-large-alt
  '#{(agent R)
     (in R A)

     (room A)
     (room B)
     (room C)
     (room D)
     (room E)
     (room F)
     (room G)
     (room H)
     (room I)
     (room J)
     (room K)
     (room L)
     (room M)
     (room N)
     (room O)
     (room P)
     (room Q)
     (room rR)
     (room S)
     (room T)

     (teleporter tele-A)
     (teleporter tele-B)
     (teleporter tele-C)
     (teleporter tele-D)
     (teleporter tele-E)
     (teleporter tele-F)
     (teleporter tele-G)
     (teleporter tele-H)
     (teleporter tele-I)
     (teleporter tele-J)
     (teleporter tele-K)
     (teleporter tele-L)
     (teleporter tele-M)
     (teleporter tele-N)
     (teleporter tele-O)
     (teleporter tele-P)
     (teleporter tele-Q)
     (teleporter tele-R)
     (teleporter tele-S)
     (teleporter tele-T)
     (powerable tele-A)
     (powerable tele-B)
     (powerable tele-C)
     (powerable tele-D)
     (powerable tele-E)
     (powerable tele-F)
     (powerable tele-G)
     (powerable tele-H)
     (powerable tele-I)
     (powerable tele-J)
     (powerable tele-K)
     (powerable tele-L)
     (powerable tele-M)
     (powerable tele-N)
     (powerable tele-O)
     (powerable tele-P)
     (powerable tele-Q)
     (powerable tele-R)
     (powerable tele-S)
     (powerable tele-T)
     (powered tele-A true)
     (powered tele-B true)
     (powered tele-C true)
     (powered tele-D true)
     (powered tele-E true)
     (powered tele-F true)
     (powered tele-G true)
     (powered tele-H true)
     (powered tele-I true)
     (powered tele-J true)
     (powered tele-K true)
     (powered tele-L true)
     (powered tele-M true)
     (powered tele-N true)
     (powered tele-O true)
     (powered tele-P true)
     (powered tele-Q true)
     (powered tele-R true)
     (powered tele-S true)
     (powered tele-T true)
     (teleporter-connection tele-A tele-B)
     (teleporter-connection tele-A tele-C)
     (teleporter-connection tele-A tele-D)
     (teleporter-connection tele-A tele-E)
     (teleporter-connection tele-A tele-F)
     (teleporter-connection tele-B tele-C)
     (teleporter-connection tele-B tele-D)
     (teleporter-connection tele-B tele-E)
     (teleporter-connection tele-B tele-F)
     (teleporter-connection tele-C tele-D)
     (teleporter-connection tele-C tele-E)
     (teleporter-connection tele-C tele-F)
     (teleporter-connection tele-D tele-E)
     (teleporter-connection tele-D tele-F)
     (teleporter-connection tele-E tele-F)
     (teleporter-connection tele-F tele-G)
     (teleporter-connection tele-G tele-H)
     (teleporter-connection tele-H tele-I)
     (teleporter-connection tele-I tele-J)
     (teleporter-connection tele-J tele-K)
     (teleporter-connection tele-K tele-L)
     (teleporter-connection tele-L tele-M)
     (teleporter-connection tele-M tele-N)
     (teleporter-connection tele-N tele-O)
     (teleporter-connection tele-O tele-P)
     (teleporter-connection tele-P tele-Q)
     (teleporter-connection tele-Q tele-R)
     (teleporter-connection tele-R tele-S)
     (teleporter-connection tele-S tele-T)

     (in tele-A A)
     (in tele-B B)
     (in tele-C E)
     (in tele-D D)
     (in tele-E C)
     (in tele-F F)
     (in tele-G J)
     (in tele-H I)
     (in tele-I H)
     (in tele-J G)
     (in tele-K L)
     (in tele-L N)
     (in tele-M O)
     (in tele-N M)
     (in tele-O K)
     (in tele-P Q)
     (in tele-Q S)
     (in tele-R P)
     (in tele-S T)
     (in tele-T rR)
     }
  )

(def state-teleport-very-large
  '#{(agent R)
     (in R A)

     (room A)
     (room B)
     (room C)
     (room D)
     (room E)
     (room F)
     (room G)
     (room H)
     (room I)
     (room J)
     (room K)
     (room L)
     (room M)
     (room N)
     (room O)
     (room P)
     (room Q)
     (room rR)
     (room S)
     (room T)
     (room U)
     (room V)
     (room W)
     (room X)
     (room Y)
     (room Z)

     (teleporter tele-A)
     (teleporter tele-B)
     (teleporter tele-C)
     (teleporter tele-D)
     (teleporter tele-E)
     (teleporter tele-F)
     (teleporter tele-G)
     (teleporter tele-H)
     (teleporter tele-I)
     (teleporter tele-J)
     (teleporter tele-K)
     (teleporter tele-L)
     (teleporter tele-M)
     (teleporter tele-N)
     (teleporter tele-O)
     (teleporter tele-P)
     (teleporter tele-Q)
     (teleporter tele-R)
     (teleporter tele-S)
     (teleporter tele-T)
     (teleporter tele-U)
     (teleporter tele-V)
     (teleporter tele-W)
     (teleporter tele-X)
     (teleporter tele-Y)
     (teleporter tele-Z)
     (powerable tele-A)
     (powerable tele-B)
     (powerable tele-C)
     (powerable tele-D)
     (powerable tele-E)
     (powerable tele-F)
     (powerable tele-G)
     (powerable tele-H)
     (powerable tele-I)
     (powerable tele-J)
     (powerable tele-K)
     (powerable tele-L)
     (powerable tele-M)
     (powerable tele-N)
     (powerable tele-O)
     (powerable tele-P)
     (powerable tele-Q)
     (powerable tele-R)
     (powerable tele-S)
     (powerable tele-T)
     (powerable tele-U)
     (powerable tele-V)
     (powerable tele-W)
     (powerable tele-X)
     (powerable tele-Y)
     (powerable tele-Z)
     (powered tele-A true)
     (powered tele-B true)
     (powered tele-C true)
     (powered tele-D true)
     (powered tele-E true)
     (powered tele-F true)
     (powered tele-G true)
     (powered tele-H true)
     (powered tele-I true)
     (powered tele-J true)
     (powered tele-K true)
     (powered tele-L true)
     (powered tele-M true)
     (powered tele-N true)
     (powered tele-O true)
     (powered tele-P true)
     (powered tele-Q true)
     (powered tele-R true)
     (powered tele-S true)
     (powered tele-T true)
     (powered tele-U true)
     (powered tele-V true)
     (powered tele-W true)
     (powered tele-X true)
     (powered tele-Y true)
     (powered tele-Z true)
     (teleporter-connection tele-A tele-B)
     (teleporter-connection tele-B tele-A)
     (teleporter-connection tele-B tele-C)
     (teleporter-connection tele-C tele-B)
     (teleporter-connection tele-C tele-D)
     (teleporter-connection tele-D tele-C)
     (teleporter-connection tele-D tele-E)
     (teleporter-connection tele-E tele-D)
     (teleporter-connection tele-E tele-F)
     (teleporter-connection tele-F tele-E)
     (teleporter-connection tele-F tele-G)
     (teleporter-connection tele-G tele-F)
     (teleporter-connection tele-G tele-H)
     (teleporter-connection tele-H tele-G)
     (teleporter-connection tele-H tele-I)
     (teleporter-connection tele-I tele-H)
     (teleporter-connection tele-I tele-J)
     (teleporter-connection tele-J tele-I)
     (teleporter-connection tele-J tele-K)
     (teleporter-connection tele-K tele-J)
     (teleporter-connection tele-K tele-L)
     (teleporter-connection tele-L tele-K)
     (teleporter-connection tele-L tele-M)
     (teleporter-connection tele-M tele-L)
     (teleporter-connection tele-M tele-N)
     (teleporter-connection tele-N tele-M)
     (teleporter-connection tele-N tele-O)
     (teleporter-connection tele-O tele-N)
     (teleporter-connection tele-O tele-P)
     (teleporter-connection tele-P tele-O)
     (teleporter-connection tele-P tele-Q)
     (teleporter-connection tele-Q tele-P)
     (teleporter-connection tele-Q tele-R)
     (teleporter-connection tele-R tele-Q)
     (teleporter-connection tele-R tele-S)
     (teleporter-connection tele-S tele-R)
     (teleporter-connection tele-S tele-T)
     (teleporter-connection tele-T tele-S)
     (teleporter-connection tele-T tele-U)
     (teleporter-connection tele-U tele-T)
     (teleporter-connection tele-U tele-V)
     (teleporter-connection tele-V tele-U)
     (teleporter-connection tele-V tele-W)
     (teleporter-connection tele-W tele-V)
     (teleporter-connection tele-W tele-X)
     (teleporter-connection tele-X tele-W)
     (teleporter-connection tele-X tele-Y)
     (teleporter-connection tele-Y tele-X)
     (teleporter-connection tele-Y tele-Z)
     (teleporter-connection tele-Z tele-Y)

     (in tele-A A)
     (in tele-B B)
     (in tele-C E)
     (in tele-D D)
     (in tele-E C)
     (in tele-F F)
     (in tele-G J)
     (in tele-H I)
     (in tele-I H)
     (in tele-J G)
     (in tele-K L)
     (in tele-L N)
     (in tele-M O)
     (in tele-N M)
     (in tele-O K)
     (in tele-P Q)
     (in tele-Q S)
     (in tele-R P)
     (in tele-S T)
     (in tele-T rR)
     (in tele-U U)
     (in tele-V W)
     (in tele-W Z)
     (in tele-X X)
     (in tele-Y V)
     (in tele-Z Y)
     }
  )



(defn test-teleport-base-small []
  (time (ops-search state-teleport-small '((in R B)) op-teleport-base))
  )

(defn test-teleport-base-medium []
  (time (ops-search state-teleport-medium '((in R C)) op-teleport-base))
  )

(defn test-teleport-base-large []
  (time (ops-search state-teleport-large '((in R G)) op-teleport-base))
  )


(defn test-teleport-guarded-one-small []
  (time (ops-search state-teleport-small '((in R B)) op-teleport-guarded-one))
  )

(defn test-teleport-guarded-one-medium []
  (time (ops-search state-teleport-medium '((in R C)) op-teleport-guarded-one))
  )

(defn test-teleport-guarded-one-large []
  (time (ops-search state-teleport-large '((in R G)) op-teleport-guarded-one))
  )


(defn test-teleport-guarded-two-small []
  (time (ops-search state-teleport-small '((in R B)) op-teleport-guarded-two))
  )

(defn test-teleport-guarded-two-medium []
  (time (ops-search state-teleport-medium '((in R C)) op-teleport-guarded-two))
  )

(defn test-teleport-guarded-two-large []
  (time (ops-search state-teleport-large '((in R G)) op-teleport-guarded-two))
  )


(defn test-teleport-guarded-three-small []
  (time (ops-search state-teleport-small '((in R B)) op-teleport-guarded-three))
  )

(defn test-teleport-guarded-three-medium []
  (time (ops-search state-teleport-medium '((in R C)) op-teleport-guarded-three))
  )

(defn test-teleport-guarded-three-large []
  (time (ops-search state-teleport-large '((in R G)) op-teleport-guarded-three))
  )